services:
  # 🕳️ Pi-hole
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /etc/pihole:/etc/pihole
      - /etc/dnsmasq.d:/etc/dnsmasq.d
    environment:
      TZ: 'Asia/Kolkata'
      FTLCONF_webserver_port: 8080
  